#!/usr/bin/env python3
"""Batch translate Chinese to English in reference files."""
import re
import os

BASE = "/home/kirky/projects/skills/cangjie"

# Translation dictionary for common terms
TRANS = {
    "模板分类法": "Template Taxonomy",
    "定义输出目标": "Defines output intent categories",
    "用于 SKILL.md 工作流": "Used in SKILL.md workflow",
    "目标识别": "Intent recognition",
    "匹配规则": "Matching rules",
    "扫描用户输入与材料": "Scan user input and materials",
    "命中 signal_words 即归入对应 goal": "Match signal_words to assign corresponding goal",
    "多 goal 命中时按": "When multiple goals hit, follow",
    "处理": "handling",
    "列候选询问用户": "list candidates and ask user",
    "无明确命中时": "When no clear match",
    "根据上下文回落到最贴近的": "Fall back to the closest based on context",
    "学会、复习、知识提炼": "Learning, review, knowledge distillation",
    "节目回顾、亮点传播": "Program recaps, highlight distribution",
    "讨论记录、责任追踪": "Discussion records, responsibility tracking",
    "阶段汇报、进展跟踪": "Periodic reporting, progress tracking",
    "多源归纳、决策支持": "Multi-source synthesis, decision support",
    "论文阅读、研究归纳": "Paper reading, research synthesis",
    "产品文档、商业计划、技术设计": "Product documents, business plans, technical design",
    "重点是课程/讲座/训练营": "Focus is courses/lectures/bootcamps",
    "重点是照着操作": "Focus is hands-on operations",
    "重点是整本非虚构书": "Focus is the entire non-fiction book",
    "重点是小说/叙事作品": "Focus is novels/narrative works",
    "单次讲座/演讲": "Single lecture/presentation",
    "解释一个概念": "Explaining a concept",
    "不确定子类型": "Uncertain subtype",
    "目标是回顾内容和传播亮点": "Intent is to review content and distribute highlights",
    "播客/访谈音频": "Podcast/interview audio",
    "视频节目": "Video program",
    "直播回顾": "Livestream recap",
    "提炼精彩片段": "Extract highlights",
    "重点是讨论过程和决策": "Focus is discussion process and decisions",
    "重点是研究输入和问答": "Focus is research input and Q&A",
    "重点是 1:1 沟通": "Focus is 1:1 communication",
    "重点是工作坊共创": "Focus is workshop co-creation",
    "需要正式归档（含 ACTION 编号/Parking Lot）": "Requires formal archiving (with ACTION numbers/Parking Lot)",
    "重点是阶段进展和指标": "Focus is periodic progress and metrics",
    "重点是周/月定期同步": "Focus is weekly/monthly periodic sync",
    "重点是向上汇报": "Focus is upward reporting",
    "重点是事故/问题": "Focus is incidents/issues",
    "重点是行动跟踪": "Focus is action tracking",
    "重点是共性主题": "Focus is common themes",
    "重点是做选择": "Focus is making choices",
    "重点是行业和事实扫描": "Focus is industry and fact scanning",
    "轻量级同类对比": "Lightweight peer comparison",
    "面向产品决策的竞品分析": "Competitive analysis for product decisions",
    "目标是读懂单篇论文": "Intent is to understand a single paper",
    "定理/证明/公式推导": "Theorems/proofs/formula derivations",
    "数据集/指标/实验对比": "Datasets/metrics/experimental comparisons",
    "系统架构/吞吐延迟": "System architecture/throughput/latency",
    "文献综述/taxonomy": "Literature survey/taxonomy",
    "建立评判框架的文献综述报告": "Literature review report with evaluation framework",
    "商业计划/融资路演": "Business plan/fundraising pitch",
    "商业模式/价值主张": "Business model/value proposition",
    "战略层": "Strategy Layer",
    "商业需求/立项": "Business requirements/project initiation",
    "市场需求": "Market requirements",
    "市场调研": "Market research",
    "竞品分析": "Competitive analysis",
    "项目任务书": "Project charter",
    "产品层": "Product Layer",
    "产品需求": "Product requirements",
    "功能需求细化": "Functional requirements refinement",
    "UIUX/配色": "UIUX/color scheme",
    "技术层": "Technical Layer",
    "技术方案": "Technical solution",
    "系统架构": "System architecture",
    "API/接口": "API/interfaces",
    "数据库设计": "Database design",
    "核心算法": "Core algorithm",
    "交付层": "Delivery Layer",
    "发布计划": "Release plan",
    "测试报告": "Test report",
    "灰度方案": "Canary release plan",
    "运营层": "Operations Layer",
    "运营手册": "Operations manual",
    "数据看板": "Data dashboard",
    "用户手册": "User manual",
    "周报月报（正式归档版）": "Weekly/monthly reports (formal archive version)",
    "退役层": "Sunset Layer",
    "复盘": "Retrospective",
    "知识沉淀": "Knowledge base",
    "正式归档纪要（含 ACTION 编号）": "Formal archive minutes (with ACTION numbers)",
    "文献综述报告（含 PRISMA）": "Literature review report (with PRISMA)",
    "不确定子层": "Uncertain sublayer",
}

# More comprehensive translations for YAML files
YAML_TRANSLATIONS = {
    # taxonomy.yaml
    "学习": "learning",
    "复习": "review",
    "笔记": "notes",
    "课程": "course",
    "讲座": "lecture",
    "教程": "tutorial",
    "训练营": "bootcamp",
    "教学视频": "instructional video",
    "书": "book",
    "书籍": "books",
    "阅读": "reading",
    "读后感": "reading response",
    "概念": "concept",
    "理解": "understanding",
    "学会": "learn",
    "知识点": "knowledge point",
    "操作步骤": "operational steps",
    "回顾": "recap",
    "节目": "program",
    "播客": "podcast",
    "视频": "video",
    "访谈节目": "interview show",
    "亮点": "highlights",
    "剪辑": "clips",
    "直播": "livestream",
    "内容消费": "content consumption",
    "节目单": "show lineup",
    "嘉宾": "guest",
    "主持人": "host",
    "会议": "meeting",
    "讨论": "discussion",
    "纪要": "minutes",
    "访谈记录": "interview record",
    "一对一": "one-on-one",
    "工作坊": "workshop",
    "共创": "co-creation",
    "决策": "decision",
    "待办": "action items",
    "责任人": "responsible person",
    "周报": "weekly report",
    "月报": "monthly report",
    "季报": "quarterly report",
    "汇报": "reporting",
    "进展": "progress",
    "状态": "status",
    "报告": "report",
    "风险": "risk",
    "阻塞": "blocker",
    "行动项": "action item",
    "优先级": "priority",
    "高管简报": "executive brief",
    "综合": "synthesis",
    "归纳": "synthesis",
    "主题综合": "theme synthesis",
    "竞品扫描": "competitive scan",
    "材料综合": "material synthesis",
    "多份材料": "multiple materials",
    "决策支持": "decision support",
    "决策备忘录": "decision memo",
    "研究": "research",
    "简报": "brief",
    "论文": "paper",
    "研究主题": "research topic",
    "公式": "formula",
    "实验": "experiment",
    "理论": "theory",
    "证明": "proof",
    "系统": "system",
    "综述": "survey",
    "文献": "literature",
    "数据集": "dataset",
    "指标": "metrics",
    "消融": "ablation",
    "商业计划": "business plan",
    "商业模式": "business model",
    "产品需求": "product requirements",
    "功能需求": "functional requirements",
    "技术需求": "technical requirements",
    "架构设计": "architecture design",
    "API文档": "API documentation",
    "数据库设计": "database design",
    "算法": "algorithm",
    "市场调研": "market research",
    "竞品分析": "competitive analysis",
    "文献综述": "literature review",
    "发布计划": "release plan",
    "测试报告": "test report",
    "灰度方案": "canary release plan",
    "运营手册": "operations manual",
    "数据看板": "data dashboard",
    "用户手册": "user manual",
    "周报月报": "weekly/monthly reports",
    "复盘": "retrospective",
    "知识沉淀": "knowledge base",
    "配色规范": "color specification",
    "项目任务书": "project charter",
    "课程笔记": "Course Notes",
    "教程操作手册": "Tutorial Playbook",
    "非虚构书籍总结": "Non-Fiction Book Summary",
    "叙事/小说书籍总结": "Fiction/Narrative Book Summary",
    "讲座摘要": "Lecture Summary",
    "概念解释": "Concept Explainer",
    "播客/访谈摘要": "Podcast/Interview Summary",
    "视频节目摘要": "Video Program Summary",
    "直播回顾": "Livestream Recap",
    "内容亮点提炼": "Content Highlights",
    "决策纪要": "Decision Minutes",
    "讨论纪要": "Discussion Minutes",
    "访谈记录": "Interview Record",
    "1:1 沟通记录": "1:1 Meeting Notes",
    "工作坊总结": "Workshop Summary",
    "项目状态报告": "Project Status Report",
    "周报/月报": "Weekly/Monthly Report",
    "高管简报": "Executive Brief",
    "风险/问题报告": "Risk/Issue Report",
    "行动跟踪表": "Action Tracker",
    "研究简报": "Research Brief",
    "论文总结（通用）": "Paper Summary (General)",
    "理论论文总结": "Theoretical Paper Summary",
    "实验论文总结": "Experimental Paper Summary",
    "系统论文总结": "Systems Paper Summary",
    "综述论文总结": "Survey Paper Summary",
    "决策备忘录": "Decision Memo",
    "主题综合": "Theme Synthesis",
    "竞品扫描（轻量级）": "Competitive Scan (Lightweight)",
    "商业需求文档（BRD）": "Business Requirements Document (BRD)",
    "市场需求文档（MRD）": "Market Requirements Document (MRD)",
    "市场调研报告": "Market Research Report",
    "竞品分析报告": "Competitive Analysis Report",
    "项目任务书（Charter）": "Project Charter",
    "产品需求文档（PRD）": "Product Requirements Document (PRD)",
    "功能需求文档（FRD）": "Functional Requirements Document (FRD)",
    "产品配色与 UIUX 规范": "Product Color & UIUX Specification",
    "技术需求文档（TRD）": "Technical Requirements Document (TRD)",
    "架构设计文档": "Architecture Design Document",
    "API 文档": "API Documentation",
    "数据库设计文档": "Database Design Document",
    "核心算法文档": "Core Algorithm Document",
    "发布计划文档": "Release Plan Document",
    "测试报告": "Test Report",
    "灰度方案": "Canary Release Plan",
    "运营手册": "Operations Manual",
    "数据看板": "Data Dashboard",
    "用户手册": "User Manual",
    "周报月报（产品族正式归档版）": "Weekly/Monthly Reports (Product Family Archive)",
    "复盘报告": "Retrospective Report",
    "知识沉淀": "Knowledge Base",
    "商业计划书（BP）": "Business Plan (BP)",
    "商业模式文档": "Business Model Document",
    "正式会议纪要": "Formal Meeting Minutes",
    "文献综述报告": "Literature Review Report",
    "需求优先级": "Requirement priority",
    "调研背景": "Research background",
    "调研方法": "Research methodology",
    "主要发现": "Key findings",
    "结论与建议": "Conclusions and recommendations",
    "投入产出": "ROI",
    "成功指标": "Success metrics",
    "风险与约束": "Risks and constraints",
    "干系人": "Stakeholders",
    "用户画像": "User personas",
    "用户痛点": "User pain points",
    "系统逻辑": "System logic",
    "状态转换": "State transitions",
    "数据流": "Data flow",
    "色彩规范": "Color specification",
    "字体规范": "Typography specification",
    "间距规范": "Spacing specification",
    "组件库": "Component library",
    "技术架构": "Technical architecture",
    "数据模型": "Data model",
    "接口定义": "Interface definition",
    "非功能设计": "Non-functional design",
    "技术选型": "Technology selection",
    "风险评估": "Risk assessment",
    "业务架构": "Business architecture",
    "应用架构": "Application architecture",
    "数据架构": "Data architecture",
    "端点列表": "Endpoint list",
    "请求响应 schema": "Request/response schema",
    "认证授权": "Authentication & authorization",
    "错误码": "Error codes",
    "版本管理": "Version management",
    "限流": "Rate limiting",
    "表结构": "Table schema",
    "索引设计": "Index design",
    "分库分表策略": "Sharding strategy",
    "数据归档方案": "Data archival plan",
    "算法概述": "Algorithm overview",
    "输入输出": "Input/output",
    "算法流程": "Algorithm flow",
    "复杂度分析": "Complexity analysis",
    "边界条件": "Boundary conditions",
    "版本规划": "Version planning",
    "环境计划": "Environment plan",
    "回滚方案": "Rollback plan",
    "监控告警": "Monitoring & alerting",
    "测试范围": "Test scope",
    "测试策略": "Test strategy",
    "覆盖率": "Coverage",
    "Bug统计": "Bug statistics",
    "遗留风险": "Residual risks",
    "发布建议": "Release recommendation",
    "灰度比例与时间节奏": "Canary ratio and timing",
    "观察指标": "Observation metrics",
    "回滚阈值": "Rollback threshold",
    "应急预案": "Emergency plan",
    "功能说明": "Feature description",
    "常见问题": "FAQ",
    "数据解读": "Data interpretation",
    "活动配置": "Activity configuration",
    "埋点规范": "Tracking specification",
    "数据口径": "Data definition",
    "帮助内容": "Help content",
    "新功能引导": "New feature guidance",
    "目标回顾": "Goal review",
    "结果评估": "Result evaluation",
    "原因分析": "Root cause analysis",
    "规律沉淀": "Pattern documentation",
    "改进动作": "Improvement actions",
    "资产归档": "Asset archival",
    "核心经验": "Core experiences",
    "踩坑记录": "Lessons learned",
    "最佳实践": "Best practices",
    "SOP提炼": "SOP extraction",
    "反模式": "Anti-patterns",
    "知识资产清单": "Knowledge asset inventory",
    "项目概述": "Project overview",
    "市场机会": "Market opportunity",
    "产品方案": "Product solution",
    "团队": "Team",
    "财务预测": "Financial projections",
    "融资计划": "Fundraising plan",
    "价值主张": "Value proposition",
    "客户细分": "Customer segments",
    "渠道": "Channels",
    "收入来源": "Revenue streams",
    "成本结构": "Cost structure",
    "关键资源": "Key resources",
    "关键活动": "Key activities",
    "合作伙伴": "Key partners",
    "议题": "Agenda items",
    "讨论": "Discussion",
    "待办事项": "Action items",
    "Parking Lot": "Parking Lot",
    "综述背景": "Review background",
    "检索策略（PRISMA）": "Search strategy (PRISMA)",
    "评判框架": "Evaluation framework",
    "主题归纳": "Theme synthesis",
    "场景化推荐": "Scenario-based recommendations",
    "研究空白": "Research gaps",
    "参考文献": "References",
    "范围与目标": "Scope & Objectives",
    "支撑证据": "Supporting evidence",
    "启示": "Implications",
    "未解决问题": "Open questions",
    "建议动作": "Recommended actions",
    "基本信息": "Basic information",
    "核心研究问题": "Core research question",
    "方法概述": "Method overview",
    "主要成果": "Key contributions",
    "关键公式或模型": "Key formulas or models",
    "实验与证据": "Experiments & evidence",
    "局限性": "Limitations",
    "后续方向": "Future directions",
    "研究主题与问题": "Research topic & problem",
    "方法与证明思路": "Method & proof approach",
    "核心定理/命题": "Core theorems/propositions",
    "成立条件与假设": "Conditions & assumptions",
    "可进一步追问的问题": "Follow-up questions",
    "实验设置": "Experimental setup",
    "消融/对比": "Ablation/comparison",
    "可以复现时需要注意的条件": "Conditions for reproducibility",
    "问题设定": "Problem setting",
    "系统设计": "System design",
    "核心机制": "Core mechanisms",
    "评测配置": "Evaluation setup",
    "性能结果": "Performance results",
    "工程权衡": "Engineering tradeoffs",
    "研究范围": "Research scope",
    "分类框架 / Taxonomy": "Classification framework / Taxonomy",
    "主要研究脉络": "Key research threads",
    "关键对比": "Key comparisons",
    "未来方向": "Future directions",
    "决策问题": "Decision problem",
    "可选方案": "Options",
    "方案1": "Option 1",
    "方案2": "Option 2",
    "权衡": "Tradeoffs",
    "推荐结论": "Recommendation",
    "后续推进": "Next steps",
    "归纳范围": "Synthesis scope",
    "反复出现的主题": "Recurring themes",
    "支持例子": "Supporting examples",
    "矛盾点": "Contradictions",
    "来源": "Sources",
    "扫描边界": "Scan boundaries",
    "比较维度": "Comparison dimensions",
    "关键参与者": "Key players",
    "空白": "Gaps",
    "机会": "Opportunities",
    "范围": "Scope",
    "作者": "Author",
    "时间": "Time",
    "材料来源": "Material sources",
    "讲者": "Speaker",
    "时长/范围": "Duration/scope",
    "学习目标": "Learning objectives",
    "内容概览": "Content overview",
    "模块拆解": "Module breakdown",
    "主题": "Topic",
    "核心概念": "Core concepts",
    "关键解释或因果链": "Key explanations or causal chains",
    "例子/演示": "Examples/demonstrations",
    "容易混淆的点": "Commonly confused points",
    "复习问题": "Review questions",
    "可执行练习": "Actionable exercises",
    "术语表": "Glossary",
    "目标": "Objective",
    "前置条件": "Prerequisites",
    "常见坑": "Common pitfalls",
    "下一步": "Next steps",
    "参考命令/资源": "Reference commands/resources",
    "输出文件": "Output files",
    "全书总览": "Full book overview",
    "核心论点": "Core arguments",
    "分部结构总览": "Part structure overview",
    "分部/章节导航": "Part/chapter navigation",
    "关键概念/模型": "Key concepts/models",
    "全书结构与论证路径": "Book structure & argumentation path",
    "可执行启发": "Actionable takeaways",
    "局限与可疑点": "Limitations & questionable points",
    "章节定位": "Chapter positioning",
    "核心问题": "Core question",
    "详细摘要": "Detailed summary",
    "本章启发": "Chapter takeaways",
    "主要人物与关系": "Main characters & relationships",
    "情节推进与转折": "Plot progression & turning points",
    "主题与母题": "Themes & motifs",
    "叙事结构与视角": "Narrative structure & perspective",
    "阅读启发/整体评价": "Reading insights/overall assessment",
    "人物焦点": "Character focus",
    "主题/象征": "Themes/symbols",
    "本章阅读要点": "Chapter reading points",
    "发言人人地图": "Speaker map",
    "核心立场": "Core stance",
    "主要贡献的话题": "Key topics contributed",
    "话题流转": "Topic flow",
    "金句": "Key quotes",
    "听众可带走的结论": "Takeaway conclusions",
    "节目分段": "Program segments",
    "核心观点": "Core insights",
    "画面要点": "Visual highlights",
    "时间线": "Timeline",
    "流程概览": "Flow overview",
    "观众提问": "Audience questions",
    "关键更新": "Key updates",
    "后续动作": "Follow-up actions",
    "参考资料": "References",
    "一句话亮点": "One-line highlights",
    "精彩片段": "Highlight clips",
    "可引用句子": "Quotable sentences",
    "复用角度": "Repurposing angles",
    "报告信息": "Report info",
    "执行摘要": "Executive summary",
    "关键进展": "Key progress",
    "风险与阻塞": "Risks & blockers",
    "下一步动作": "Next actions",
    "需要支持": "Support needed",
    "已完成工作": "Completed work",
    "进行中工作": "In-progress work",
    "阻碍项": "Blockers",
    "下个周期计划": "Next period plan",
    "经验总结": "Lessons learned",
    "战略更新": "Strategic updates",
    "待决策事项": "Pending decisions",
    "主要风险": "Key risks",
    "附录": "Appendix",
    "问题概述": "Issue overview",
    "影响范围": "Impact scope",
    "原因分析": "Root cause analysis",
    "缓解措施": "Mitigation measures",
    "依赖事项": "Dependencies",
    "升级路径": "Escalation path",
    "行动列表": "Action list",
    "截止时间": "Deadline",
    "状态备注": "Status notes",
    "复盘节奏": "Retrospective cadence",
    "会议信息": "Meeting info",
    "参与人": "Participants",
    "后续步骤": "Next steps",
    "发言人观点": "Speaker perspectives",
    "受访人背景": "Interviewee background",
    "访谈主题": "Interview topics",
    "回答与洞察": "Answers & insights",
    "关键原话": "Key quotes",
    "后续跟进": "Follow-up",
    "决策影响": "Decision impact",
    "当前状态": "Current status",
    "最近进展": "Recent progress",
    "阻碍": "Blockers",
    "达成的动作": "Agreed actions",
    "发展议题": "Development topics",
    "情绪信号": "Sentiment signals",
    "活动流程": "Activity flow",
    "产出物": "Deliverables",
    "参与者反馈": "Participant feedback",
    "视觉要点": "Visual highlights",
    "商业目标": "Business objectives",
    "调研背景": "Research background",
    "调研方法": "Research methodology",
    "竞品矩阵": "Competitive matrix",
    "差异化机会": "Differentiation opportunities",
    "护城河分析": "Moat analysis",
    "应战策略": "Competitive response strategy",
    "项目背景": "Project background",
    "项目目标": "Project objectives",
    "范围边界": "Scope boundaries",
    "里程碑": "Milestones",
    "核心团队": "Core team",
    "资源预算": "Resource budget",
    "产品概述": "Product overview",
    "用户旅程": "User journey",
    "功能详述": "Feature details",
    "验收标准": "Acceptance criteria",
    "非功能需求": "Non-functional requirements",
    "埋点": "Event tracking",
    "依赖": "Dependencies",
    "色彩规范": "Color specification",
    "字体规范": "Typography specification",
    "间距规范": "Spacing specification",
    "组件库": "Component library",
    "交互原型": "Interactive prototype",
    "文案规范": "Copywriting specification",
}

def translate_file(filepath):
    """Translate Chinese text in a file to English."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Apply translations (longest first to avoid partial matches)
    sorted_trans = sorted(TRANS.items(), key=lambda x: -len(x[0]))
    for zh, en in sorted_trans:
        content = content.replace(zh, en)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Translated: {os.path.relpath(filepath, BASE)}")

# Process files
files_to_translate = [
    "references/taxonomy.yaml",
    "references/registry.yaml",
    "references/families/learning.yaml",
    "references/families/media.yaml",
    "references/families/meeting.yaml",
    "references/families/product.yaml",
    "references/families/business.yaml",
    "references/families/analysis.yaml",
    "references/README.md",
    "references/templates-index.md",
    "references/guides/output-skeletons.md",
    "references/guides/detail-policy.md",
    "references/guides/skeletons-analysis.md",
    "references/guides/skeletons-media.md",
    "references/guides/skeletons-learning.md",
    "references/guides/skeletons-meeting.md",
    "references/guides/skeletons-business.md",
    "references/guides/template-selection.md",
    "references/guides/template-authoring.md",
    "references/guides/examples.md",
    "references/guides/api-docs.md",
]

for f in files_to_translate:
    fp = os.path.join(BASE, f)
    if os.path.exists(fp):
        translate_file(fp)

print("\nAll reference files translated!")
